version: "3.7"
services:
  mcserver:
    image: itzg/minecraft-server
    container_name: mcserver
    env_file: .env
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "./data:/data"
      - "./mods:/data/mods"
      - "./config:/data/config"
      - "./datapacks:/data/world/datapacks"
