---
- include_tasks:
    file: backup.yml
    apply:
      tags: backup
    tags:
      - backup
- include_tasks:
    file: reset.yml
    apply:
      tags: reset
    tags:
      - reset
- include_tasks:
    file: setup.yml
    apply:
      tags: setup
    tags:
      - setup
- include_tasks:
    file: start.yml
    apply:
      tags: start
    tags:
      - start
- include_tasks:
    file: stop.yml
    apply:
      tags: stop
    tags:
      - stop
