# Setup server
---
- name: archive server files
  delegate_to: localhost
  ansible.builtin.archive:
    path:
      - docker-compose.yml
      - .env
      - datapacks
      - modpack
      - config
      - worlds
    dest: server.tgz
- name: copy server zip to remote
  ansible.builtin.copy:
    src: server.tgz
    dest: ~
- name: unarchive server
  ansible.builtin.unarchive:
    src: ~/server.tgz
    dest: ~/
    remote_src: yes
  notify:
    - restart
