# Setup server
---
- name: setup server for the first time
  hosts: minecraft

  tasks:
    - name: archive server files
      delegate_to: localhost
      ansible.builtin.archive:
        path:
          - ../docker-compose.yml
          - ../.env
          - ../datapacks
          - ../mods
          - ../config
        dest: "../server.tgz"
    - name: copy server zip to remote
      ansible.builtin.copy:
        src: ../server.tgz
        dest: "{{ remote_path }}"
    - name: unarchive server
      ansible.builtin.unarchive:
        src: "{{ remote_path }}/server.tgz"
        dest: "{{ remote_path }}"
        remote_src: yes
