name = "mkamadeus-survival-server-modpack"
author = "mkamadeus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a7434ccdfa92a3df4618fe486e10804de02815d4f94b23f6fcdbdc7c62e8c0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.1-beta.6"
